scheme: "Default Dark"
author: "Chris Kempson (http://chriskempson.com)"
base00: "151515"
base01: "AC4142"
base02: "90A959"
base03: "F4BF75"
base04: "6A9FB5"
base05: "AA759F"
base06: "75B5AA"
base07: "D0D0D0"
base08: "505050"
base09: "AC4142"
base0A: "90A959"
base0B: "F4BF75"
base0C: "6A9FB5"
base0D: "AA759F"
base0E: "75B5AA"
base0F: "F5F5F5"
